.github/workflows/pr_checker.yml
core/base/src/main/res/layout/layout_common_appbar.xml

[FEAT/#2] Github Action CI Setting

---

.github/workflows/pr_checker.yml
app/src/main/java/com/teumteum/teumteum/di/RetrofitModule.kt
app/src/main/java/com/teumteum/teumteum/di/ServiceModule.kt
build-logic/convention/src/main/java/com/teumteum/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
core/data/build.gradle.kts

[FEAT/#6] Retrofit Module Setting

---

app/src/debug/java/com/teumteum/teumteum/FlipperSetUp.kt
app/src/main/java/com/teumteum/teumteum/MyApp.kt
app/src/main/java/com/teumteum/teumteum/di/RetrofitModule.kt
app/src/release/java/com/teumteum/teumteum/FlipperSetUp.kt
gradle/libs.versions.toml

[FEAT/#8] Flipper Setting

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
app/src/main/res/drawable/sample_left.xml
app/src/main/res/layout/activity_group_list.xml
app/src/main/res/layout/item_group_list.xml
core/domain/src/main/java/com/teumteum/domain/entity/Group.kt

- close : #5 
- 화면 UI 구현입니다.
- 리스트 클릭했을 때 리스터까지만 구현했습니다.
- 폰트나 텍스트 스타일은 컴포넌트 적용 후 변경 예정입니다.

[FEAT/#5] 모임탐색 UI 구현

---

app/build.gradle.kts
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/TeumTeumFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/location/TeumTeumFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/location/TeumTeumViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/location/custom/CharacterView.kt
app/src/main/res/color/selector_character.xml
app/src/main/res/drawable-night/ic_location_background.xml
app/src/main/res/drawable/ic_character_pink.xml
app/src/main/res/drawable/ic_check_dark.xml
app/src/main/res/drawable/ic_location_background.xml
app/src/main/res/layout/custom_character_view.xml
app/src/main/res/layout/fragment_teum_teum.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

- closed #22
- 현위치 위경도 좌표값 수신 코드 세팅
- 캐릭터 커스텀 뷰 추가
- 캐릭터 커스텀 뷰 터치 시 체크 박스 visibility 활성/비활성화
- 일부 drawable을 다크/라이트 안 나누고 올렸습니다. 위경도 좌표값 수신 코드 세팅이 주 목적인 branch라 관련 부분은 추후 다른 branch 통해서 수정할 계획입니다. UI 마진값도 일부 부정확한데 같은 맥락입니다.
- 위치 권한 요청 작업은 다른 branch에서 진행할 계획입니다.
https://github.com/depromeet/TeumTeum-Android/assets/89737271/440b1dbc-593e-4642-b0af-b7c45ec048b4

[FEAT/#22] 현위치 위경도 좌표값 수집

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/TopicActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/TopicAdapter.kt
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/TopicViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/teumteum/topic/model/Topic.kt
app/src/main/res/drawable-night/ic_balance_background_1.xml
app/src/main/res/drawable-night/ic_balance_background_2.xml
app/src/main/res/drawable-night/ic_balance_background_3.xml
app/src/main/res/drawable-night/ic_balance_background_4.xml
app/src/main/res/drawable-night/ic_balance_background_5.xml
app/src/main/res/drawable/ic_balance_background_1.xml
app/src/main/res/drawable/ic_balance_background_2.xml
app/src/main/res/drawable/ic_balance_background_3.xml
app/src/main/res/drawable/ic_balance_background_4.xml
app/src/main/res/drawable/ic_balance_background_5.xml
app/src/main/res/layout/activity_topic.xml
app/src/main/res/layout/item_topic.xml

- closed #50
- 뷰페이저 세팅
- 앞면 다크/라이트 모드별 drawable 추가 
- 코드 세팅만 해놓았고 아직 페이지간 연결은 안 된 상태입니다. 
- UI 디테일은 페이지 연결 이후 보충할 예정입니다
https://github.com/depromeet/TeumTeum-Android/assets/89737271/a4c2d73a-594d-473a-a0db-483ffc5d5728

[Feat/#50] 대화 주제 뷰페이저 구현

---

app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
app/src/main/res/color/selector_bottom_menu.xml
app/src/main/res/drawable-night/ic_bell.xml
app/src/main/res/drawable/ic_bell.xml
app/src/main/res/drawable/ic_bottom_navi_familiar.xml
app/src/main/res/drawable/ic_bottom_navi_home.xml
app/src/main/res/drawable/ic_bottom_navi_mypage.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/item_recommend_meet.xml
app/src/main/res/menu/main_bottom_menu.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/strings.xml

- closed #69
- 다크/라이트 색상 적용
- 바텀 네비바 메뉴 아이콘 및 이름 수정
- 
https://github.com/depromeet/TeumTeum-Android/assets/89737271/9adbea23-3cbe-41c5-a3c8-6cc1590d0124

[FEAT/#69] 홈 화면 다크/라이트 적용, 네비바 메뉴 수정

---

app/src/debug/java/com/teumteum/teumteum/FlipperSetUp.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListAdapter.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
app/src/main/res/layout/fragment_home.xml
core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
core/domain/src/main/java/com/teumteum/domain/repository/GroupRepository.kt

- close #67
- 모임 리스트 무한 스크롤 구현
- 모임 검색 무한 스크롤 구현
- 홈 화면 로고 클릭 시 최상단으로 스크롤
- Paging3로 구현하려다 시간 관계 상 리팩토링에서 하는 것으로 결정했습니다 🧐

[FEAT/#67] 무한 스크롤 구현

---

app/src/main/java/com/teumteum/teumteum/presentation/onboarding/AccessLocationActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/signin/SignInActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/signin/SocialWebViewActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/SignUpViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/area/PreferredAreaFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/community/CommunityFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/interests/GetInterestFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/intro/CardIntroActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/job/CurrentJobFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/job/ReadyJobFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/mbti/GetMbtiFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/modal/AreaModalBottomSheet.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/terms/TermsWebViewActivity.kt
app/src/main/java/com/teumteum/teumteum/util/SigninUtils.kt
app/src/main/java/com/teumteum/teumteum/util/SignupUtils.kt
app/src/main/res/values/strings.xml

[FIX/#66] 반복되는 상수 유틸로 분리

---

app/src/main/java/com/teumteum/teumteum/presentation/group/search/SearchActivity.kt
app/src/main/res/layout/activity_search.xml

[REFACTORING/#92] 모임 검색 기능 & UX 개선

---

app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListActivity.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/GroupListViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/home/HomeFragment.kt
app/src/main/res/layout/activity_group_list.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/values/strings.xml

- close #94 
- 홈 화면 지역 리스트 없을 경우 EmptyView 추가
- topic 별 리스트 없을 경우 EmptyView 추가

[FEAT/#94] 모임 없을 때 Empty 안내 추가

---

app/src/main/res/layout/item_group_list.xml

- close #96
- 모임 리스트 divider 색상 수정

[UI/#96] 모임 리스트 divider 색상 수정

---

app/src/main/res/layout/activity_group_list.xml

- closed #98 
- 모임 리스트 다크모드 대응

[fix/#98] 모임 리스트 다크모드 대응

---

app/src/main/java/com/teumteum/teumteum/presentation/mypage/setting/viewModel/MyPageViewModel.kt
build-logic/convention/src/main/java/com/teumteum/convention/src/main/kotlin/Constants.kt

[FIX/#118] 버전 코드, 친구 목록 아이콘 수정

---

app/src/main/java/com/teumteum/teumteum/presentation/mypage/MyPageScreen.kt

[FIX/#118] 카드 뒷면 수정

---

app/src/main/res/layout/fragment_common_dialog.xml

- closed #136
- CommonDialog 취소버튼 색상 수정
-

[FIX/#136] CommonDialog 취소버튼 색상 수정

---

core/data/src/main/java/com/teumteum/data/interceptor/AuthInterceptor.kt

- close #153 
- 토큰 리프레시 url 수정

[FIX/#153] 토큰 리프레시 url 수정

---

.github/workflows/release_builder.yml

- close #152
- GithubAction CD 구현

[SETTING/#152] GithubAction CD Apk 파일 추출 자동화 구현

---

README.md

- 오타 수정
-  MOUDLE 🙅‍♂️ -> MODULE
@ddingmin ㅋㅋ

[docs] 오타 수정

---

README.md

[DOCS/#158] readme 수정

---

app/src/main/java/com/teumteum/teumteum/MyApp.kt
app/src/main/java/com/teumteum/teumteum/presentation/splash/SplashActivity.kt

- open #160 
- 알림 백그라운드 / 포그라운드 실행 구분

[FIX/#160] 알림 기능 수정

---

app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewFriendDetailFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewViewModel.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/complete/CardCompleteFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/fix/CardFixFragment.kt
app/src/main/java/com/teumteum/teumteum/presentation/signup/name/GetNameFragment.kt
app/src/main/java/com/teumteum/teumteum/util/ResMapper.kt
app/src/main/java/com/teumteum/teumteum/util/custom/view/BackCardView.kt
core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
core/data/src/main/java/com/teumteum/data/service/GroupService.kt

- open #160 
- 회원가입 이름 입력 캡션 수정
- 카드 후면 GOAL 텍스트 색상 반영
- 유저 리뷰 수정

[FIX/#160] 카드 후면 및 유저 리뷰 수정

---

app/src/main/java/com/teumteum/teumteum/presentation/group/review/ReviewViewModel.kt
core/data/src/main/java/com/teumteum/data/datasource/remote/RemoteGroupDataSource.kt
core/data/src/main/java/com/teumteum/data/model/request/RequestReviewFriend.kt
core/data/src/main/java/com/teumteum/data/repository/GroupRepositoryImpl.kt
core/data/src/main/java/com/teumteum/data/service/GroupService.kt

- open #160 
- 임시 조치 : 모임 참여자 3명 이상인 경우에만 리뷰 알림 전송
- 유저 리뷰 수정

[FIX/#160] 유저 리뷰 수정

---

app/src/main/java/com/teumteum/teumteum/config/TeumMessagingService.kt

- close #166
- 푸시알림 Silent Push로 변경(백그라운드에서도 동작하도록 변경)

[FIX/#166] 푸시알림 동작 방식 변경
